version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: weekly
    groups:
      site-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major

  - package-ecosystem: npm
    directory: /vscode-extension
    schedule:
      interval: weekly
    groups:
      vscode-extension-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
      - dependency-name: "@types/vscode"
        versions:
          - ">=1.126.0"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
